apiVersion: v1
kind: Service
metadata:
  name: shop-backend-service
spec:
  type: ClusterIP
  selector:
    app: shop-backend-label
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shop-frontend-service
spec:
  type: ClusterIP
  selector:
    app: shop-frontend-label
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: shop-frontend-route
spec:
  host: devshop.apps.ocp4.innershift.sodigital.io
  path: /
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: shop-frontend-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: shop-backend-route
spec:
  host: devshop.apps.ocp4.innershift.sodigital.io
  path: /api
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: shop-backend-service
